### ISSUE TITLE
Add stop button

### ISSUE THREAD

**Issue by somecho** [somecho/p5-cljs-web-editor#1]
Add a stop button to stop and remove running sketches from view (similar to how the P5 editor does it).

The button should have a different color from the run button, indicating a stop action. Preferable from the neutral or slate tailwind colorscheme.

**Comment by Technobromo** [comment]
Hey

I would like to contribute.

**Comment by somecho** [comment]
Feel free to clone the dev branch and make a PR to the dev branch.
